### PR TITLE
chore: Make UPX go faster

### PR DESCRIPTION
**Pull request by david-doit-intl**
Signed-off-by: david-doit-intl <david@doit-intl.com>

### CODE REVIEW

**Comment by stepanstipl** [comment]
Can we get a more detailed analysis of the impact on size for different binaries here? The "10MB" seems to be a fit rough (from latest nightly):
```bash
$ ls -lh  kubent*
-rwxr-xr-x@ 1 stepan  staff   6.7M  5 May 03:43 kubent
-rw-r--r--@ 1 stepan  staff   6.7M  7 May 11:26 kubent-nightly-0.4.0-7-ge158834-linux-amd64.tar.gz
```

**Comment by david-doit-intl** [comment]
```bash
du -sh release-artifacts/*
8.3M    kubent
8.1M    kubent-dev-linux-amd64.tar.gz
```
I just removed brute and set it fastest. I think this is reasonable comprise.

**Comment by david-doit-intl** [comment]
Whilst I haven't removed UPX entirely, the builds are much faster.

**Comment by stepanstipl** [comment]
What about checking previous runs? What brute does is effectively runs over all (or almost, there's `--extra-brute` too 😉 ) possible combinations, and then picks the best result. So we should be able to check which ones worked best from previous runs and use that without any impact on size. I guess this might be different for different platforms 🤔, but worth checking I think.

**Comment by david-doit-intl** [comment]
Binaries are roughly 8-9 MB each

**Comment by david-doit-intl** [comment]
--extra-brute way too long :robot:

**Comment by stepanstipl** [comment]
hint:
```bash 
$ upx --fileinfo kubent                                                                                                                                           0
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

kubent [amd64-linux.elf, linux/amd64]
   7047840 bytes, compressed by UPX 13, method 14, level 10, filter 0x00/0x00
```

**Comment by david-doit-intl** [comment]
Found it:

Level: 10
Method: 14

--lzma <-

**Review by stepanstipl — APPROVED** [review]
Looks good 👍

**Pull request merged**
