### PR TITLE
fix: Arch detection for aarch64

### LINKED ISSUE #283: Running install-kubent fails on linux/arm64
Since kubent has a binary available for linux/arm64. I tried to install it via the `install-kubent `script.
However because `uname -m` on Linux returns `aarch64` it fails. On MacOS, `uname -m` returns `arm64`.

```
# uname -s -m
Linux aarch64
# sh -c "$(curl -sSL https://git.io/install-kubent)"
>>> kubent installation script <<<
> Detecting latest version
> Downloading version 0.5.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     35      0 --:--:-- --:--:-- --:--:--    35
tar: invalid magic
tar: short read
```

There is a workaround using the `TARGET_ARCH` env, but it would be nice if the script supported this directly.

```
# uname -s -m
Linux aarch64
# TARGET_ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')" sh -c "$(curl -sSL https://git.io/install-kubent)"
>>> kubent installation script <<<
> Detecting latest version
> Downloading version 0.5.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   670  100   670    0     0   2401      0 --:--:-- --:--:-- --:--:--  2401
100 8808k  100 8808k    0     0  5532k      0  0:00:01  0:00:01 --:--:-- 13.0M
> Done. kubent was installed to /usr/local/bin/.
```

### PR DESCRIPTION
**Pull request by Staphylo**
Use the same sed trick for x86_64 -> amd64

Fixes #283

### CODE REVIEW

**Comment by dark0dave** [comment]
Hi @Staphylo thanks for your contribution, if the tests pass we will merge.

**Comment by Staphylo** [comment]
@dark0dave just changed commit message and PR message, let me know if there's anything else.

**Comment by dark0dave** [comment]
> @dark0dave just changed commit message and PR message, let me know if there's anything else.

Thanks will run test again if they pass we can merge.

**Review by dark0dave — APPROVED** [review]
LGTM

**Comment by dark0dave** [comment]
@Staphylo ah sorry to be a stickler, could you [sign your commit](https://docs.github.com/articles/about-gpg/)?

**Review by dark0dave — CHANGES_REQUESTED** [review]
See above if you wouldn't mind signing the commit. We will get this merged.

**Pull request closed without merging**
