### PR TITLE
Fix missing characters and incorrect uppercase

### PR DESCRIPTION
**Pull request by Syphdias**
Hey, I noticed a few typos in the README and thought I should fix them. Cheers!

### CODE REVIEW

**Comment by Syphdias** [comment]
no

**Review by apgiorgi — APPROVED** [review]
LGTM

**Review by migueldelucasdoit — APPROVED** [review]
Thanks @Syphdias for your collaboration. Much appreciated!!!

**Comment by femrtnz** [comment]
Hi  @Syphdias I believe you will need to sign your commit so we can merge this. Are you able to follow this [doc](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

**Comment by Syphdias** [comment]
I even rebased it :slightly_smiling_face:

**Comment by apgiorgi** [comment]
Thanks again, @Syphdias

**Pull request merged**
