### PR TITLE
fix(contributions): Add Contributing file

### PR DESCRIPTION
**Pull request by dark0dave**
Applogies for the other pr, it eventually got out of hand. So I am introducing a contribution document. See the referenced message again. Once again appologies for the spam.

> Seeing how there has been some confusion over how to operate this repo, I have added more details for the maintianers to discuss.

> @migueldelucasdoit Please read and approve if you agree.

> It is desirable that these rules are followed. Not just for the sake of following them but for the purpose of maintaining standards.

### CODE REVIEW

**Review by femrtnz — COMMENTED** [review]
Hey @dark0dave so far LGTM
Can you include details about release process and tagging as well? Thanks

**Review by migueldelucasdoit — APPROVED** [review]
Hey @dark0dave thanks for taking the time to compose this document.
Much appreciated!!! LGTM.

**Comment by dark0dave** [comment]
> Can you include details about release process and tagging as well? Thanks

Yes I'll add that in annother pr! Thank you!

**Review by femrtnz — APPROVED** [review]

**Comment by migueldelucasdoit** [comment]
Hey @dark0dave can you please try now merging the PR? 
Thanks in advance.

**Pull request merged**
