### PR TITLE
fix(context): Removing unneeded global context

### PR DESCRIPTION
**Pull request by dark0dave**
Please do not merge this until its ready.

### CODE REVIEW

**Comment by migueldelucasdoit** [comment]
Hello @dark0dave we would like to find the best way to collaborate together. Can you please explain in more detail what you're trying to do with this PR? Happy to discuss this with you in person and with the rest of the team.

**Comment by dark0dave** [comment]
> Hello @dark0dave we would like to find the best way to collaborate together. Can you please explain in more detail what you're trying to do with this PR? Happy to discuss this with you in person and with the rest of the team.

I mean now your happy to collborate???

**Comment by dark0dave** [comment]
Standards in this project have been either ignored or just gone unnoticed.

**Comment by dark0dave** [comment]
I'll state it for brevity again. Do not introduce unneed global dependancies...

**Comment by dark0dave** [comment]
This still isn't ready please don't  merge, I need to correct the tests.

**Comment by femrtnz** [comment]
@dark0dave please let us know when this is ready to review, thanks!

**Comment by dark0dave** [comment]
@femrtnz @migueldelucasdoit this pr is now ready. In future if we could avoid introducing global context varriables without discuss that would be great. So I don't have to spend my free time correcting issues.

image

**Comment by dark0dave** [comment]
Maintianing this repo is not a race.

**Comment by dark0dave** [comment]
The repeated code is required for tests. We can clean that up later. Can I get a review from @migueldelucasdoit @femrtnz.

The intent here is as I have said in line with removing global context. In an ideal situtation we do not share a global context. So instead I have introduced cusomizable printer options as I am sure many more printing requests will arise. 

This leaves room for the future, rather than placing in a global context, which created a tight binding accross the sub packages. I know this is the natural inclination of golang to add a context, but we want to keep these packages seperate. Your welcome to introduce a context for indivual packages, see pkg/judge/rego.go for a nice example of how this is done. 

We try to use the config package to hold configuration for the whole of kubent, so by introducing a context you effectively stored configuration in two places which is not desirable. Please try to keep this in mind when adding changes.

**Review by femrtnz — APPROVED** [review]
Hey @dark0dave thanks for detailed explanation. I agree it is a better approach removing the global context.

Whats is your plan to fix the tests?  Looking the duplications I can see benefits on having those duplicated there to improve readability. Maybe we could ignore duplications on test files in Sonar? Or create a some helper functions?

**Comment by dark0dave** [comment]
> Hey @dark0dave thanks for detailed explanation. I agree it is a better approach removing the global context.
> 
> Whats is your plan to fix the tests? Looking the duplications I can see benefits on having those duplicated there to improve readability. Maybe we could ignore duplications on test files in Sonar? Or create a some helper functions?

Lets solve the duplications in annother pr.  I have created an issue to track it. Open to suggestions!

**Comment by dark0dave** [comment]
https://github.com/doitintl/kube-no-trouble/issues/652

**Pull request merged**
