### PR TITLE
chore(clean): Clean up mess from double merge master into prs

### PR DESCRIPTION
**Pull request by dark0dave**
A maintainer decide merge master into several prs. Creating a history nightmare. So now we need to clean and go through all the changes made.

### CODE REVIEW

**Comment by dark0dave** [comment]
If its not obivious don't merge this until its ready. Apparenently that needs to be said.

**Comment by migueldelucasdoit** [comment]
Hello @dark0dave. It seems that we did something wrong when merging pending PRs. It seems that some of the changes done to the precommit and cliff configuration files were lost in the process and you're trying to restore them.
We apologize for any inconvenience this might have caused you.

**Review by migueldelucasdoit — APPROVED** [review]
LGTM

**Comment by dark0dave** [comment]
I TOLD YOU @migueldelucasdoit  NOT TO MERGE THIS CAN YOU NOT READ....

**Comment by dark0dave** [comment]
> We apologize for any inconvenience this might have caused you.

No, you double merged master into those prs. Don't do that.

**Comment by dark0dave** [comment]
There is no misunderstanding don't merge master into PRs

**Comment by dark0dave** [comment]
I also have no finished correcting the repo.....

**Comment by dark0dave** [comment]
In case this process is not obivious to you. Grant approval, then allow me to merge the pr.

**Pull request merged**
