### PR TITLE
fix: Default the Helm manifest namespace to the release namespace

### PR DESCRIPTION
**Pull request by meringu**
closes: #67

### CODE REVIEW

**Comment by david-doit-intl** [comment]
LGTM, lets let @stepanstipl have a look.

**Comment by stepanstipl** [comment]
Thanks @meringu, I think this great! 👍  I'm reasonably confident this will work for Helm v3, as the release info is stored in the same namespace where the release is deployed.

However for v2, won't this always be the namespace where the Tiller is deployed (I think `kube-system` by default)?

TL;DR: You mentioned it worked in your setup in #67, were you able to test this with Helm v2?

**Comment by meringu** [comment]
Yes we have a very large helmv2 deployment still.

Tiller can go in any namespace, it only defaults to kube-system. This is configured with the --tiller-namespace flag. However, when you install a release you can override the namespace with the --namespace flag.

This seems to report correctly over our hundreds of helmv2 deprecation warnings. The release namespace ends up being the default namespace to deploy the resources, just like helmv3.

**Review by stepanstipl — APPROVED** [review]
OK, thanks for confirming this, sounds good. 👍

**Pull request merged**
