### PR TITLE
ci: update checkout action to lastest

### PR DESCRIPTION
**Pull request by dark0dave**
Part of https://github.com/doitintl/kube-no-trouble/issues/306

### CODE REVIEW

**Comment by dark0dave** [comment]
what a mess...

**Comment by dark0dave** [comment]
> @dark0dave would this allow us to remove the changes in #305? In particular the
> 
> ```
> git config --global --add safe.directory "$GITHUB_WORKSPACE" || true
> ```
> 
> is causing the following issue when run locally (used to work):
> 
> ```
> $ gmake test
> test -z "$(opa fmt -l pkg/rules/rego/*)"
> test -z "$(go fmt ./...)"
> ./scripts/git-check-commits.sh
> ./scripts/git-check-commits.sh: line 10: GITHUB_WORKSPACE: unbound variable
> gmake: *** [Makefile:96: test-git] Error 1
> ```
> 
> ... so I'm wondering if this would allow us to drop that change?

So I tried removing it and because we clone it still there are still some issues.

**Comment by dark0dave** [comment]
@stepanstipl fixed :)

**Review by stepanstipl — APPROVED** [review]
LGTM

**Pull request merged**
