### PR TITLE
fix: Move autoscaling/v2beta1 removed to Kubernetes 1.25

### LINKED ISSUE #459: 1.26 removal of horizontal pod autoscaler autoscaling/v2beta1 is incorrect
Kubernetes removed `autoscaling/v2beta1` in kubernetes 1.25, not 1.26. In 1.26, `autoscaling/v2beta2` was removed.

1.25 `autoscaling/v2beta1` removal - https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
1.26 `autoscaling/v2beta2` removal - https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126

Link to code within this repository: https://github.com/doitintl/kube-no-trouble/blob/4582f531c1e91fc4adf844b7b9ba6052bfa20256/pkg/rules/rego/deprecated-1-26.rego#L24

This causes a false positive when running `kubent` against a cluster which outputs `autoscaling/v2beta1` as being removed in 1.26 when in actual fact it is removed in 1.25.

### PR DESCRIPTION
**Pull request by johngmyers**
Fixes #459

### CODE REVIEW

**Comment by stepanstipl** [comment]
Thanks @johngmyers, this looks good 👍 . Can you pls. also move the tests[^1] accordingly? (and rebase on the current master if possible).

Cheers :tada:.

[^1]: https://github.com/doitintl/kube-no-trouble/blob/d0ef3cbbe478d67aa1aa83a75d5c13c701a69ba0/test/rules_126_test.go#L9

**Comment by johngmyers** [comment]
@stepanstipl the `git-check-commits.sh` script appears to be enforcing a capitalization requirement that is not in the Conventional Commits specification and is not mentioned in `README.md`. The apiVersion in question is typically rendered in lower case.

**Comment by stepanstipl** [comment]
Hi @johngmyers, you're totally correct here. Do you think that for now, you can perhaps rephrase the commit? Maybe smth. like `fix: Move autoscaling/v2beta1 to Kubernetes 1.25 group` or similar.

On the topic of the capital letters - I guess it's a personal preference. Not a strong one, so potentially open to discussion (I simply think it doesn't matter too much). But you're right that it would be a good idea to mention this in the docs 🙏 .

**Comment by johngmyers** [comment]
@stepanstipl I changed the commit message

**Review by stepanstipl — APPROVED** [review]
Thanks, LGTM. 👍 🎉

**Comment by stepanstipl** [comment]
Oh, one more thing - sorry, I noticed only when trying to merge. Can you pls. sign the commit? [^1][^2]

[^1]: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
[^2]: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by johngmyers** [comment]
@stepanstipl I'll have to create a key. This signing requirement is another thing that isn't but should be mentioned in the Development section of README.md.

**Comment by dark0dave** [comment]
> @stepanstipl I'll have to create a key. This signing requirement is another thing that isn't but should be mentioned in the Development section of README.md.

@johngmyers, I will sort that out thanks!

**Comment by johngmyers** [comment]
@stepanstipl commit is signed now.

**Comment by stepanstipl** [comment]
👍 thanks!

**Pull request merged**
