### PR TITLE
chore: Add brew installation method

### PR DESCRIPTION
**Pull request by devenes**
Added brew installation method to README with reference to https://formulae.brew.sh/formula/kubent

### CODE REVIEW

**Comment by dark0dave** [comment]
Could you give us the scripts you used to build this? I am not sure we want to publicly endorse a homebrew package we did not make.

**Comment by stepanstipl** [comment]
@dark0dave - what doy you think about adding a "3rd party" section to the readme.

I'm not sure we want to maintain this (and possibly many other packages/distributions), but maybe making it clear it's 3rd party effort, and linking to it would be a good compromise?

_(Also I believe the Homebrew formulas have to live in the HB repo [^1])_

[^1]: https://github.com/Homebrew/homebrew-core/blob/055ae78415b61ecf1fa3de32b76b8a149855f903/Formula/k/kubent.rb

**Comment by devenes** [comment]
Thanks for valuable feedback @dark0dave @stepanstipl.

In response to your suggestions, I edited the document to include sections for both manual and third-party methods. Additionally, I added a note for the third-party approach.

For referencing the source, I used [formula](https://formulae.brew.sh/formula/kubent) link. Kindly request to review these changes and share any further recommendations.

**Review by stepanstipl — APPROVED** [review]
I'm happy with this, thanks for the changes @devenes 👍

**Review by dark0dave — APPROVED** [review]

**Comment by devenes** [comment]
I apologize for that. I believe I have fixed the issue. Could you please check it?

**Comment by dark0dave** [comment]
@devenes pre-commit passed look like we are good!

**Pull request merged**
