### PR TITLE
Remove Helm v2 support and upgrade helm/v3, k8s.io/apimachinery and k8s.io/client-go

### LINKED ISSUE #390: kubent 0.6.0: crash on first run on mac, after every boot
Hi, sorry for more trouble reported.

I have noticed that kubent 0.6.0 always crashes for me the first time after I boot my mac with the below stack trace.
I am able to recreate this every time, and once I get this crash once and run again, it works until next boot.

You can see that I run it then successfully just by starting same command.

I am not sure if it is the cause for it but I also noticed that after this happens, often there is an error related to `.kube/config.lock` file (file exists error) and I have to delete it otherwise other tools (Lens) will not be able to view a k8s cluster, maybe it is related and could be helpful to solve this issue in kubent:

Error reported by Lens:

```bash
E1020 10:45:43.152586 3818 proxy_server.go:147] Error while proxying request: acquiring a token for authorization header: storing the refreshed token in configuration: persisting the configuration: open /Users/tomaszkluczkowski/.kube/config.lock: file exists
```

This is what I have to do to make Lens work after config.lock becomes stuck:

```bash
rm /Users/tomaszkluczkowski/.kube/config.lock
```

It can be that is **completely unrelated** so take it with a pinch of salt. I would ignore it initially in debugging, just noticed this started happening since I started using kubent 0.6.0....

Thx for looking into it :) 

Tom

Stack trace of the `kubent` crash:

```bash
6:30PM INF >>> Kube No Trouble `kubent` <<<
6:30PM INF version 0.6.0 (git sha 126e47b9b45550a45404b599c546bf911ffae571)
6:30PM INF Initializing collectors and retrieving data
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x10649bf]

goroutine 1 [running]:
runtime.throw({0x217f87b?, 0x30?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0003dd5d8 sp=0xc0003dd5a8 pc=0x10365dd
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc0003dd628 sp=0xc0003dd5d8 pc=0x104c185
aeshashbody()
	/usr/local/go/src/runtime/asm_amd64.s:1366 +0x39f fp=0xc0003dd630 sp=0xc0003dd628 pc=0x10649bf
runtime.mapiternext(0xc0003c7d80)
	/usr/local/go/src/runtime/map.go:936 +0x2eb fp=0xc0003dd6a0 sp=0xc0003dd630 pc=0x100fb2b
runtime.mapiterinit(0x1?, 0x7?, 0x1?)
	/usr/local/go/src/runtime/map.go:863 +0x236 fp=0xc0003dd6c0 sp=0xc0003dd6a0 pc=0x100f7f6
reflect.mapiterinit(0x2bba3000?, 0xc0000e0ce0?, 0x2bd82fff?)
	/usr/local/go/src/runtime/map.go:1375 +0x19 fp=0xc0003dd6e8 sp=0xc0003dd6c0 pc=0x1060db9
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0001b9500, 0xc000010838, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:291 +0x236 fp=0xc0003dd858 sp=0xc0003dd6e8 pc=0x15d9b76
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x1ff03e0?, 0xc0003dd801?, 0xc0000bac78?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22 fp=0xc0003dd880 sp=0xc0003dd858 pc=0x15d25c2
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001b9770, 0x1efeb47?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56 fp=0xc0003dd8f8 sp=0xc0003dd880 pc=0x15e73f6
github.com/json-iterator/go.(*structEncoder).Encode(0xc0001b97d0, 0x8000?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765 fp=0xc0003dd9e0 sp=0xc0003dd8f8 pc=0x15e7e05
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0000bac60?, 0xc00069fa00?, 0xc0003dda70?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xb0 fp=0xc0003dda30 sp=0xc0003dd9e0 pc=0x15def50
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x1ff03e0?, 0xc0003c7c01?, 0xc0000bac78?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22 fp=0xc0003dda58 sp=0xc0003dda30 pc=0x15d25c2
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001fe960, 0x1f2f068?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56 fp=0xc0003ddad0 sp=0xc0003dda58 pc=0x15e73f6
github.com/json-iterator/go.(*structEncoder).Encode(0xc000262a50, 0xc00004ec30?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765 fp=0xc0003ddbb8 sp=0xc0003ddad0 pc=0x15e7e05
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x1ff03e0?, 0x15e6c01?, 0xc0000bac78?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22 fp=0xc0003ddbe0 sp=0xc0003ddbb8 pc=0x15d25c2
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000262d80, 0x1efeb07?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56 fp=0xc0003ddc58 sp=0xc0003ddbe0 pc=0x15e73f6
github.com/json-iterator/go.(*structEncoder).Encode(0xc000262de0, 0x1fa7840?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765 fp=0xc0003ddd40 sp=0xc0003ddc58 pc=0x15e7e05
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc000010f78, 0xc00010d238, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_slice.go:42 +0x327 fp=0xc0003dddf8 sp=0xc0003ddd40 pc=0x15dfa47
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000317d10, 0x1f0457e?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56 fp=0xc0003dde70 sp=0xc0003dddf8 pc=0x15e73f6
github.com/json-iterator/go.(*structEncoder).Encode(0xc000317f50, 0x0?, 0xc0000bac60)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765 fp=0xc0003ddf58 sp=0xc0003dde70 pc=0x15e7e05
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000132be0?, 0x0?, 0x0?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xb0 fp=0xc0003ddfa8 sp=0xc0003ddf58 pc=0x15def50
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0006211d0, 0xc00010d1e0, 0xc0001342d0?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82 fp=0xc0003ddfe0 sp=0xc0003ddfa8 pc=0x15d1b82
github.com/json-iterator/go.(*Stream).WriteVal(0xc0000bac60, {0x205ef80, 0xc00010d1e0})
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x166 fp=0xc0003de050 sp=0xc0003ddfe0 pc=0x15d0ea6
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000132be0, {0x205ef80, 0xc00010d1e0})
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9 fp=0xc0003de0e8 sp=0xc0003de050 pc=0x15c7fa9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x1ee4878?, {0x23a7c28?, 0xc00010d1e0?}, {0x239fda0, 0xc0006379e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/json/json.go:305 +0x6d fp=0xc0003de180 sp=0xc0003de0e8 pc=0x15f9a6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00007e140, {0x23a7c28, 0xc00010d1e0}, {0x239fda0, 0xc0006379e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/json/json.go:300 +0xfc fp=0xc0003de1e0 sp=0xc0003de180 pc=0x15f999c
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc000360820, {0x23a7bd8?, 0xc0000baba0}, {0x239fda0, 0xc0006379e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/versioning/versioning.go:244 +0x946 fp=0xc0003de568 sp=0xc0003de1e0 pc=0x16078e6
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc000360820, {0x23a7bd8, 0xc0000baba0}, {0x239fda0, 0xc0006379e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/versioning/versioning.go:184 +0x106 fp=0xc0003de5c8 sp=0xc0003de568 pc=0x1606f46
k8s.io/apimachinery/pkg/runtime.Encode({0x2c24f000, 0xc000360820}, {0x23a7bd8, 0xc0000baba0})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/codec.go:50 +0x64 fp=0xc0003de608 sp=0xc0003de5c8 pc=0x1392bc4
k8s.io/client-go/tools/clientcmd.Write(...)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/loader.go:469
k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0000aabd0}, 0xc0000aac60, 0xc0000aac90, 0xc0000aacf0, {0xc00004af98, ...}, ...}, ...)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/loader.go:422 +0xa8 fp=0xc0003de680 sp=0xc0003de608 pc=0x1e7e388
k8s.io/client-go/tools/clientcmd.ModifyConfig({0x23b5dc0, 0xc00007e3c0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0006378c0}, 0xc0006378f0, 0xc000637920, ...}, ...)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/config.go:280 +0xcd8 fp=0xc0003deda8 sp=0xc0003de680 pc=0x1e7a6d8
k8s.io/client-go/tools/clientcmd.(*persister).Persist(0xc0000e0de0, 0xc0000ddc20)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/config.go:363 +0x11a fp=0xc0003dee98 sp=0xc0003deda8 pc=0x1e7b07a
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc000670200, 0xc00010cd10)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/plugin/pkg/client/auth/azure/azure.go:276 +0x34b fp=0xc0003deef8 sp=0xc0003dee98 pc=0x1eb358b
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc000670200)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/plugin/pkg/client/auth/azure/azure.go:194 +0x247 fp=0xc0003df0b8 sp=0xc0003deef8 pc=0x1eb26e7
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc00036aba0, 0xc00027aa00)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/plugin/pkg/client/auth/azure/azure.go:125 +0x6f fp=0xc0003df218 sp=0xc0003df0b8 pc=0x1eb1fcf
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00036ac20, 0xc00027a900)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/transport/round_trippers.go:159 +0x350 fp=0xc0003df310 sp=0xc0003df218 pc=0x1b27c30
net/http.send(0xc00027a800, {0x23a1b40, 0xc00036ac20}, {0x2133ac0?, 0x10bb901?, 0x2deae60?})
	/usr/local/go/src/net/http/client.go:251 +0x5f7 fp=0xc0003df508 sp=0xc0003df310 pc=0x13455b7
net/http.(*Client).send(0xc0001b80c0, 0xc00027a800, {0x8?, 0xc000477610?, 0x2deae60?})
	/usr/local/go/src/net/http/client.go:175 +0x9b fp=0xc0003df580 sp=0xc0003df508 pc=0x1344e3b
net/http.(*Client).do(0xc0001b80c0, 0xc00027a800)
	/usr/local/go/src/net/http/client.go:715 +0x8fc fp=0xc0003df770 sp=0xc0003df580 pc=0x13471bc
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:581
k8s.io/client-go/rest.(*Request).request(0xc0000334a0, 0xc000477968?)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/rest/request.go:801 +0x4cd fp=0xc0003df900 sp=0xc0003df770 pc=0x1b44d6d
k8s.io/client-go/rest.(*Request).Do(0xc0000334a0)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/rest/request.go:873 +0xaf fp=0xc0003df988 sp=0xc0003df900 pc=0x1b4594f
k8s.io/client-go/discovery.(*DiscoveryClient).ServerVersion(0x1f970a0?)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/discovery/discovery_client.go:408 +0x74 fp=0xc0003dfad0 sp=0xc0003df988 pc=0x1b4c5d4
github.com/doitintl/kube-no-trouble/pkg/collector.(*kubeCollector).GetServerVersion(0x0?)
	/__w/kube-no-trouble/kube-no-trouble/pkg/collector/kube.go:71 +0x33 fp=0xc0003dfba8 sp=0xc0003dfad0 pc=0x1e85a13
main.getServerVersion(0x0, {0xc0006714c0?, 0x3, 0xc00058fdc8?})
	/__w/kube-no-trouble/kube-no-trouble/cmd/kubent/main.go:88 +0x96 fp=0xc0003dfc00 sp=0xc0003dfba8 pc=0x1ed61b6
main.main()
	/__w/kube-no-trouble/kube-no-trouble/cmd/kubent/main.go:123 +0x405 fp=0xc0003dff80 sp=0xc0003dfc00 pc=0x1ed6665
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0003dffe0 sp=0xc0003dff80 pc=0x1038df2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0003dffe8 sp=0xc0003dffe0 pc=0x10674a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000074fb0 sp=0xc000074f90 pc=0x10391b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc000074fe0 sp=0xc000074fb0 pc=0x103904d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x10674a1
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000075790 sp=0xc000075770 pc=0x10391b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000757c8 sp=0xc000075790 pc=0x1024657
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000757e0 sp=0xc0000757c8 pc=0x10192c6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000757e8 sp=0xc0000757e0 pc=0x10674a1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x206328f8dfb2?, 0x2b3705?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000075f70 sp=0xc000075f50 pc=0x10391b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x2deafe0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000075fa0 sp=0xc000075f70 pc=0x10226b3
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:622 +0x65 fp=0xc000075fc8 sp=0xc000075fa0 pc=0x1022ca5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000075fe0 sp=0xc000075fc8 pc=0x1019266
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x10674a1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 17 [finalizer wait]:
runtime.gopark(0x0?, 0xc000074670?, 0x2b?, 0x6c?, 0xc000074770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000074628 sp=0xc000074608 pc=0x10391b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc0000747e0 sp=0xc000074628 pc=0x10183cf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x10674a1
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 18 [chan receive]:
runtime.gopark(0xc0000706d8?, 0x103efdb?, 0x20?, 0x7?, 0x1055bc5?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc0000706c8 sp=0xc0000706a8 pc=0x10391b6
runtime.chanrecv(0xc0000520c0, 0xc0000707a0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49b fp=0xc000070758 sp=0xc0000706c8 pc=0x10067fb
runtime.chanrecv2(0x12a05f200?, 0x0?)
	/usr/local/go/src/runtime/chan.go:447 +0x18 fp=0xc000070780 sp=0xc000070758 pc=0x1006338
k8s.io/klog.(*loggingT).flushDaemon(0x0?)
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x6a fp=0xc0000707c8 sp=0xc000070780 pc=0x1240f8a
k8s.io/klog.init.0.func1()
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0x26 fp=0xc0000707e0 sp=0xc0000707c8 pc=0x123ee26
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000707e8 sp=0xc0000707e0 pc=0x10674a1
created by k8s.io/klog.init.0
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xef

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000070f50 sp=0xc000070f30 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000070fe0 sp=0xc000070f50 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000070fe8 sp=0xc000070fe0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x20632996f137?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000071750 sp=0xc000071730 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000717e0 sp=0xc000071750 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000717e8 sp=0xc0000717e0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x2063299bb48f?, 0x3?, 0x10?, 0x7a?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000450750 sp=0xc000450730 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0004507e0 sp=0xc000450750 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0004507e8 sp=0xc0004507e0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x2063299bb591?, 0x3?, 0x8c?, 0x2b?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000071f50 sp=0xc000071f30 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000071fe0 sp=0xc000071f50 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x206329971c11?, 0x1?, 0xe2?, 0xe3?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000450f50 sp=0xc000450f30 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000450fe0 sp=0xc000450f50 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000450fe8 sp=0xc000450fe0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x206329971ba1?, 0xc000046160?, 0x18?, 0x14?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000072750 sp=0xc000072730 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000727e0 sp=0xc000072750 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x20632996f173?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000451750 sp=0xc000451730 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0004517e0 sp=0xc000451750 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0004517e8 sp=0xc0004517e0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x2e27140?, 0x1?, 0xd5?, 0x6f?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000072f50 sp=0xc000072f30 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000072fe0 sp=0xc000072f50 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x206329975c57?, 0x1?, 0xe4?, 0xe6?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000076750 sp=0xc000076730 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000767e0 sp=0xc000076750 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 24 [GC worker (idle)]:
runtime.gopark(0x2063299bbca0?, 0x3?, 0xd4?, 0x6?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000073750 sp=0xc000073730 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000737e0 sp=0xc000073750 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x2063299751dd?, 0x1?, 0xb8?, 0xa3?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000451f50 sp=0xc000451f30 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000451fe0 sp=0xc000451f50 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000451fe8 sp=0xc000451fe0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x2063299bde9f?, 0x3?, 0x69?, 0x5d?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000073f50 sp=0xc000073f30 pc=0x10391b6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000073fe0 sp=0xc000073f50 pc=0x101b411
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x10674a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 6 [select]:
runtime.gopark(0xc00044ffa0?, 0x3?, 0x0?, 0x0?, 0xc00044ff82?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00044fe08 sp=0xc00044fde8 pc=0x10391b6
runtime.selectgo(0xc00044ffa0, 0xc00044ff7c, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc00044ff48 sp=0xc00044fe08 pc=0x10485dc
net/http.setRequestCancel.func4()
	/usr/local/go/src/net/http/client.go:397 +0x8b fp=0xc00044ffe0 sp=0xc00044ff48 pc=0x134646b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00044ffe8 sp=0xc00044ffe0 pc=0x10674a1
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:396 +0x44a
```

Notice that immediate subsequent run of `kubent` succeeds...

```bash
 ~  kubent                                                    2 х  at 18:30:13
6:30PM INF >>> Kube No Trouble `kubent` <<<
6:30PM INF version 0.6.0 (git sha 126e47b9b45550a45404b599c546bf911ffae571)
6:30PM INF Initializing collectors and retrieving data
6:30PM INF Target K8s version is 1.23.12
6:30PM INF Retrieved 151 resources from collector name=Cluster
6:30PM INF Retrieved 0 resources from collector name="Helm v2"
6:30PM WRN failed to discover supported resources for : groupVersion shouldn't be empty
6:30PM WRN failed to discover supported resources for : groupVersion shouldn't be empty
6:30PM WRN failed to discover supported resources for : groupVersion shouldn't be empty
6:30PM WRN failed to discover supported resources for : groupVersion shouldn't be empty
6:30PM WRN failed to discover supported resources for : groupVersion shouldn't be empty
6:30PM INF Retrieved 230 resources from collector name="Helm v3"
6:30PM INF Loaded ruleset name=custom.rego.tmpl
6:30PM INF Loaded ruleset name=deprecated-1-16.rego
6:30PM INF Loaded ruleset name=deprecated-1-22.rego
6:30PM INF Loaded ruleset name=deprecated-1-25.rego
6:30PM INF Loaded ruleset name=deprecated-1-26.rego
6:30PM INF Loaded ruleset name=deprecated-future.rego
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
...
...
...
```

### PR DESCRIPTION
**Pull request by stepanstipl**
This PR removes Helm v2 and upgrades core dependencies `helm/v3`, `k8s.io/apimachinery` and `k8s.io/client-go` to their latest stable versions. This in turn fixes #390, #391, #400, and #65. Also removes any references to Helm v2 from docs and fixes tests using the K8S dynamic fake client.

### CODE REVIEW

**Comment by dark0dave** [comment]
Aside from the code smells this looks good to me

**Review by dark0dave — APPROVED** [review]

**Comment by stepanstipl** [comment]
Thanks @dark0dave.

As to the failed checks:
- Snyk - complains about deps pulled in due to Helm v3 - but certainly not worse than the current state using the old ones :), I think we can ignore.
- Code smells - all about duplication -> constants
  1) flags in `cmd/kubent/main_test.go` - not a new code
  2) new code in`pkg/collector/cluster_test.go` - I don't think using constants here is an improvement, plus those are tests
  3) same, in `pkg/collector/cluster_test.go` - same as above

In general, I don't think introducing constants in the new code mentioned above improves readability or anything. As to the one in the existing code - I prefer not to make unrelated changes other than those required for the PR.

But let me know if you think any of the above are important in your opinion to address, I'm happy to do that. 👍

**Comment by dark0dave** [comment]
Yeah thats fine then @stepanstipl

**Comment by dark0dave** [comment]
Lets get this in 
I want to remove v2, but we should do a new version, 0.7 or something for it

**Comment by stepanstipl** [comment]
Yep, I would say 0.7 once we confirm the changes worked. Might want to squeeze one small thing in - I noticed some noisy logs to stdout/err? after upgrading the client, will create issue about it.

**Pull request merged**
